apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kotlin-service
  name: kotlin-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  selector:
    matchLabels:
      app: kotlin-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kotlin-service
    spec:
      containers:
        - env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: MONGO_PASSWORD
            - name: SLACK_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: slack-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: SLACK_TOKEN_ID
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                  key: SLACK_CHANNEL_ID
          name: kotlin-service
          image: oyvindis/kotlin-service
          imagePullPolicy: Always
      restartPolicy: Always
