apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kotlin-service
  name: kotlin-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  selector:
    app: kotlin-service
  ports:
    - port: 8080
