logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/climate?authSource=admin&authMechanism=SCRAM-SHA-1
---
spring:
  config.activate.on-profile: develop
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/climate?authSource=admin&authMechanism=SCRAM-SHA-1
---
spring:
  config.activate.on-profile: integration-test