security:
  disabled: false

spring:
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/climate?authSource=admin&authMechanism=SCRAM-SHA-1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-22151406.okta.com/oauth2/default
