logging:
  level:
    root: WARN
    no: ${LOG_LEVEL:DEBUG}
    org.springframework: WARN
    org.springframework.web: WARN
    org.apache.jena: ERROR

server:
  servlet:
    encoding:
      force-response: true
  forward-headers-strategy: framework

security:
  disabled: false

kafka:
  bootstrapAddress: ${KAFKA_BOOTSTRAP_HOST:10.0.0.22}:${KAFKA_BOOTSTRAP_PORT:31172}
  topics:
    sensor: sensor

slack:
  security:
    token: ${SLACK_TOKEN_ID}
  channel:
    id: ${SLACK_CHANNEL_ID}

spring:

  profiles:
    default: local